# Generated by Django 3.2.3 on 2021-08-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.IntegerField(choices=[('option 1', 1), ('option 2', 2), ('option 3', 3), ('option 4', 4)])),
            ],
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='usersubjectrelation',
            options={'ordering': ['user']},
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=1000)),
                ('option2', models.CharField(max_length=1000)),
                ('option3', models.CharField(max_length=1000)),
                ('option4', models.CharField(max_length=1000)),
                ('assignment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.assignment')),
                ('test', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.test')),
            ],
        ),
    ]
