# Generated by Django 3.2.6 on 2021-08-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210831_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.IntegerField(choices=[(1, 'option 1'), (2, 'option 2'), (3, 'option 3'), (4, 'option 4')], default=0),
            preserve_default=False,
        ),
    ]
