# Generated by Django 3.2.3 on 2021-08-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_studentscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='duedate',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='duedate',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subject',
            name='meet_link',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
