# Generated by Django 3.2.3 on 2021-08-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210831_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
